server:
  port: 8080
  servlet:
    context-path: /lcx
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?serverTimezone=UTC
    username: root
    password: ok
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html




mybatis:
  mapper-locations: classpath:/mappings/*.xml
  configuration:
    auto-mapping-behavior: full
  type-aliases-package: com.zb.test.entity

